### ISSUE TITLE
Publish MolecularFramework as maven repository on Github

### ISSUE THREAD

**Issue by e15d5605** [glycoinfo/MolecularFramework#1]
## 背景
GlyCosmosプロジェクトではソフトウェアをMavenで管理し、Nexusサーバーに構築されたMavenリポジトリに公開している\
Nexusはプロジェクト内の開発者がソフトウェアを開発する際に、ソースコードの依存関係を解決するのに役立てられている\
特に、MolecularFrameworkはNexusに公開されたライブラリの一つであり、様々なソフトウェアで参照されている

## 問題点
Nexusサーバーは少人数で管理されており、システム障害の復旧などの余分な負担が発生しうる\
Nexusに障害が発生した場合、MolecularFrameworkを利用したソフトウェアの開発や利用が困難になる

## 目的
MolecularFrameworkの公開を、Nexusから別のプラットフォームへの移行を検討する

## 検討案
GLICミーティングでMolecularFrameworkの管理方法について議論が行われ、Githubで管理するという結論が得られている\
このことを考慮して、Githubを利用したライブラリの公開方法を調査し、以下の2つの方法が明らかとなった

1. Github Actionsを利用した公開方法
2. Githubにmavenリポジトリを構築する方法

1はGithubが提供しているサービスだが、ライブラリの公開および利用の両方でGithubのアカウント認証が必要だった\
一方で、2の方法は開発者がライブラリを公開をする際にGithubのアカウント認証を必要とするが、利用者側のアカウント認証は不要だった\
以上の点から、2の方法を用いたライブラリの公開を行なった

## 方法
glycoinfoにライブラリ公開用の[MavenRepository](https://github.com/glycoinfo/MavenRepository)を作成した \
以下の流れで、MavenRepositoryにライブラリを登録するための設定を行なった
1. https://github.com/glycoinfo/MolecularFramework/issues/1#issuecomment-1006351851
2. https://github.com/glycoinfo/MolecularFramework/issues/1#issuecomment-1006353632
3. https://github.com/glycoinfo/MolecularFramework/issues/1#issuecomment-1006357801
4. https://github.com/glycoinfo/MolecularFramework/issues/1#issuecomment-1006358603

**Comment by e15d5605** [comment]
### Github workflowの作成

リポジトリにプッシュされた際にGithub Actionsを実行するためのワークフローを作成する\
ワークフローを保管するためにプロジェクト直下に`.github/workflows`というディレクトリを作成した
今回はmavenパッケージを作成するため、`maven.yml`というファイルを以下の構成で保管した\

> .github/workflows/maven.yml

maven.ymlの構成は以下の通りである

```
name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Release Maven package
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} mvn -B -s settings.xml deploy
```
